version: '2'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    #container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8086:80

  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_PASSWORD=${DB_PASSWORD}

  myapp:
    tty: true
    # image: mintnapatsorn/wotregister:1.7
    image: bitnami/laravel:5.7.19
    # build:
      # context: .
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}

    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:   #ที่ต้องมีการ volume เพื่อกันข้อมูลหายไป เมื่อทำการ start/up
      - ./:/app
      # - .env:/app/.env
      
